#Makefile

# Created on: 2015-09-21
#     Author: JakeYang

source_files +=	dxflib/dxf.c \
		dxflib/dxf_header.c \
		dxflib/dxfile.c \
		dxflib/entities_3dsolid.c \
		dxflib/entities_arc.c \
		dxflib/entities.c \
		dxflib/entities_circle.c \
		dxflib/entities_ellipse.c \
		dxflib/entities_image.c \
		dxflib/entities_line.c \
		dxflib/entities_lwpolyline.c \
		dxflib/entities_mtext.c \
		dxflib/entities_point.c \
		dxflib/entities_polyline.c \
		dxflib/entities_spline.c \
		dxflib/entities_text.c \
		dxflib/dxf_map.c \
		dxflib/dxf_tables.c \
		dxflib/dxf_tables_entries.c \
		dxflib/dxf_tables_ltype.c \
		dxflib/dxf_tables_vport.c

header_files +=	dxflib/c_message.h \
		dxflib/dxfbase.h \
		dxflib/dxf.h \
		dxflib/dxf_header.h \
		dxflib/dxfile.h \
		dxflib/entities_3dsolid.h \
		dxflib/entities_arc.h \
		dxflib/entities_circle.h \
		dxflib/entities_ellipse.h \
		dxflib/entities.h \
		dxflib/entities_image.h \
		dxflib/entities_line.h \
		dxflib/entities_lwpolyline.h \
		dxflib/entities_mtext.h \
		dxflib/entities_point.h \
		dxflib/entities_polyline.h \
		dxflib/entities_spline.h \
		dxflib/entities_text.h \
		dxflib/version.h \
		dxflib/dxf_map.h \
		dxflib/dxf_tables.h \
		dxflib/dxf_tables_entries.h \
		dxflib/dxf_tables_ltype.h \
		dxflib/dxf_tables_vport.h
